# Generated by Django 5.2 on 2025-04-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
